---
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: flux-inflation
  namespace: flux-system
spec:
  interval: 3m0s
  path: ./overlay/dev
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-inflation
  validation: client
  decryption:
    provider: sops