---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whatever
spec:
  template:
    spec:
      tolerations:
        - key: "bb-nodes"
          operator: "Exists"
          effect: "NoSchedule"