git:
    credentials:
        password: repo1-dso-milMxxwxTsY79aKGSsRsRtU
sops:
    kms:
        - arn: arn:aws:kms:us-east-2:960125005494:alias/sops-manual
          created_at: "2022-07-15T18:19:29Z"
          enc: AQICAHh36bD+d47F9YtXvdr1BCJT2k4NPr5eMspt2X9UG+SUjgEB/1r3XMqKfPqLVXz75R8KAAAAfjB8BgkqhkiG9w0BBwagbzBtAgEAMGgGCSqGSIb3DQEHATAeBglghkgBZQMEAS4wEQQMXgCItcLVC9LDc/7BAgEQgDuE3/nDm4IdeLsj0+O1FkHpA5RdwpZMBxmsTlm/fvjoN/1H/i6LVSE+4ihEFRUeDAK5Ga9nTUv8FaRmzw==
          aws_profile: ""
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-07-15T18:19:44Z"
    mac: ENC[AES256_GCM,data:GoHAw2BcIuENBe/3rpm1G2J8dwHCFXu+5U4KwAijWsnm7cyz7uf4NCtdtdHgQ3Nk9uAZ4bPvT0B4rkKQp7w/nIrRZrZiBiqa0lnb2awLehSA7FOn7JjPLE5O4C7IE+kSKmSYEvy4QDnSsL7ZyRnQ7f9IAmlmyapSqMr16m1zJ64=,iv:shsFadHvNFFj0FFW94HPEx/kFYeM34ceFCNpH91INWw=,tag:n3SfqiUY0CS8XMJJ3jvUnw==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
