---
bases:
  - ../../base

resources:
  - flux

configMapGenerator:
  - name: environment
    namespace: bigbang
    behavior: merge
    files:
      - values.yaml=values.yaml

patchesStrategicMerge:
  - environment-bb-secret.enc.yaml