---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: flux-system

resources:
  - git::https://repo1.dso.mil/platform-one/big-bang/bigbang.git/base/flux?ref=1.37.0
  - cosmic-inflation-repo.yaml

patchesStrategicMerge:
  - gotk-patches.yaml
